name: PR Agent Approval

on:
  pull_request_review:
    types: [submitted]
jobs:
  auto_approve:
    if: github.event.pull_request.base.ref == 'main' && github.event.review.state == 'approved' && github.event.review.user.login == 'codiumai-pr-agent-free[bot]'
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        if: ${{ !env.GITHUB_CLI }}
        run: sudo apt-get install -y gh

      - name: Approve PR
        run: gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
